### ISSUE TITLE
Distinguished Name not available

### ISSUE THREAD

**Issue by SecureThisShit** [Kevin-Robertson/Powermad#1]
Hi,

i just tried to add an ADIDNS-Node Entry for two different AD-Environments. The script was executed with a valid AD-User. But the default distinguished Names "CN=MicrosoftDNS,DC=DomainDNSZones" are not available on both Environments. So theese containers are not enabled in the default settings? I could not find another valid distinguished Name for the ADIDNS Zones.

The verbose Error Message for trying to add a note:
Exception when calling "SendRequest" with 1 argument(s): "The object does not exist".

Greetings

**Comment by Kevin-Robertson** [comment]
Can you verify the correct distinguished name through ADSI edit and compare it to the one being built with New-ADIDNSNode (-verbose switch)? I haven't really been able to test with anything in ForestDNSZones. That's the other main location. I have a -Partition parameter to easily switch between DomainDNSZones and ForestDNSZones.

**Comment by SecureThisShit** [comment]
I can not find the "CN=MicrosoftDNS,DC=DomainDNSZones" Path neither the "ForestDNSZones" Path in both AD-Environments.
The ADIDNS Zone Path (Distinguished Name), which is found with -Verbose switch is not available. Maybe i should setup a new Test-Environment.

**Comment by Kevin-Robertson** [comment]
Are they environments that have been around for awhile? The legacy location is CN=MicrosoftDNS,CN=System. For that one, you should be able to just connect to the default context with ADSI Edit and drill down.

**Comment by SecureThisShit** [comment]
You are right. In a complete fresh environment the MicrosoftDNS Container is below the System Container. I found it, and it works! Im going to close this issue.

**Comment by SecureThisShit** [comment]
I tried it in a WS2k16 environment. No Changes from default settings. Also in my productive environment the MicrosoftDNS CN was below the System CN.
The Full DN for a wildcard Node was like this: DC=*,DC=testdomain.demo.local,CN=MicrosoftDNS,CN=System,DC=testdomain,DC=demo,DC=local

**Comment by Kevin-Robertson** [comment]
Interesting, I'll have to do more research into when CN=System comes into play. I should probably just add a function that can search AD for the zone location.

Thanks!

**Comment by SecureThisShit** [comment]
Thank you for the good work and fast replies !
